services:
  - type: web
    name: ecommerce-mascotas
    env: node
    buildCommand: cd server && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: shuttle.proxy.rlwy.net
      - key: DB_PORT
        value: 21840
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: anJkMDnhTJoXaMDjgYFpfmkMBUskRZFu
      - key: DB_NAME
        value: ecommerce_mascotas
      - key: CLOUDINARY_CLOUD_NAME
        value: djkl0swu2
      - key: CLOUDINARY_API_KEY
        value: 816256627638173
      - key: CLOUDINARY_API_SECRET
        value: W47P54JMJjyIy9c6Wv2jmeyxb0A
      - key: JWT_SECRET
        value: miTiendaMascotas_2024_xK9#mP2$qL8
      - key: MP_ACCESS_TOKEN
        value: APP_USR-7278906658711153-050519-a563fe94de6738ca2c0b45cb7230628c-1737686913
      - key: MP_PUBLIC_KEY
        value: APP_USR-f230c4af-9901-4ba2-91b8-1de5a3db91ea
      - key: FRONTEND_URL
        value: https://maulu.onrender.com
