services:
  - type: web
    name: ecommerce-mascotas
    env: node
    buildCommand: cd server && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: shuttle.proxy.rlwy.net
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: anJkMDnhTJoXaMDjgYFpfmkMBUskRZFu
      - key: DB_NAME
        value: ecommerce_mascotas
      - key: CLOUDINARY_CLOUD_NAME
        value: djkl0swu2
      - key: CLOUDINARY_API_KEY
        value: 816256627638173
      - key: CLOUDINARY_API_SECRET
        value: W47P54JMJjyIy9c6Wv2jmeyxb0A
      - key: JWT_SECRET
        value: tu_clave_secreta_jwt_muy_segura_2024